#!/bin/bash

source ./helpers

echo "* Installing ..."

echo "*"
echo "*"
echo "*"

# make pid file service
makePidFile() {
    sudo touch $pidFile
    sudo chmod -R 0777 $pidFile
    echo "* Created pid file > [ $pidFile ]"
    echo "*"
}

# make log file service
makeLogFile() {
    sudo touch $logFile
    sudo chmod -R 0777 $logFile
    echo "* Created log file > [ $logFile ]"
    echo "*"
}

if [ ! -f $pidFile ]; then
    makePidFile
fi

if [ ! -f $logFile ]; then
    makeLogFile
fi

echo "* Created log file > [ $logFile ]"
echo "*"
echo "* We need to premission to copy of needed files to filesystem ..."
echo "*"
sudo cp ./laravel /etc/init.d/laravel_queue

sudo cp ./.service /etc/systemd/system/laravel_queue.service

sudo chmod 664 /etc/systemd/system/laravel_queue.service

sudo chmod +x /etc/init.d/laravel_queue

echo "* Service is ready to use , show something special :)"