#!/bin/bash
# @author Alireza Josheghani <josheghani.dev@gmail.com>
# @since 26 Dec 2016
# @package Laravel queue service installer

pidFile="/var/run/QueueService.pid"

logFile="/var/log/QueueService.log"

echo "* Installing ..."

echo "*"
echo "*"
echo "*"

# make pid file service
makePidFile() {
    sudo touch $pidFile
    sudo chmod -R 0777 $pidFile
    echo "* Created pid file > [ $pidFile ]"
    echo "*"
}

# make log file service
makeLogFile() {
    sudo touch $logFile
    sudo chmod -R 0777 $logFile
    echo "* Created log file > [ $logFile ]"
    echo "*"
}

if [ ! -f $pidFile ]; then
    makePidFile
fi

if [ ! -f $logFile ]; then
    makeLogFile
fi

echo "* Created log file > [ $logFile ]"
echo "*"
echo "* We need to premission to copy of needed files to filesystem ..."
echo "*"
sudo cp ./laravel /etc/init.d/laravel_queue

sudo chmod +x /etc/init.d/laravel_queue

echo "* Service is ready to use , show something special :)"