#!/bin/bash

source ./helpers

echo "* Installing ..."

echo "*"
echo "*"
echo "*"

# make pid file service
makePidFile() {
    sudo touch $pidFile
    sudo chmod -R 0777 $pidFile
    echo "* Created pid file > [ $pidFile ]"
    echo "*"
}

# make log file service
makeLogFile() {
    sudo touch $logFile
    sudo chmod -R 0777 $logFile
    echo "* Created log file > [ $logFile ]"
    echo "*"
}

if [ ! -f $pidFile ]; then
    makePidFile
fi

if [ ! -f $logFile ]; then
    makeLogFile
fi

echo "* Service is ready to use , show something special :)"