#!/bin/bash
# @author Alireza Josheghani <josheghani.dev@gmail.com>
# @since 26 Dec 2016
# @package Laravel queue service

pidFile="/var/run/QueueService.pid"

logFile="/var/log/QueueService.log"

if [ ! -f "./artisan" ]; then
    projectPath=$2
else
    projectPath='.'
fi

checkProgress() {
    progress="$(pgrep -fl queue:work)"

    if [[ $progress ]]; then
        echo "The service already started!"
        exit 0
    fi
}

connection=$3

# start the service
start() {
    checkProgress
    if [ ! -f "$projectPath/artisan" ]; then
        echo "The directory does not have the artisan file"
        exit 0
    fi

    echo "* Starting web server laravel queue worker"
    echo "*"

    start-stop-daemon --start --background -m --oknodo --pidfile ${pidFile} --exec \
        /usr/bin/php $projectPath/artisan queue:work $connection & > ${logFile} 2>&1

    echo $!>$pidFile
    echo "* Started"
}

# stop the service
stop() {
    echo "* Stopping web server laravel queue worker"
    start-stop-daemon --stop --quiet --oknodo --pidfile $pidFile
    echo "*"
    echo "* Stopped"
}

case $1 in
"start")
    start
   ;;
"stop")
    stop
   ;;
"restart")
    stop
    start
   ;;
*)
   echo "Usage: $0 {start|stop|restart}"
esac

exit 0